"""empty message

Revision ID: 108c4cf52be6
Revises: 5a5b7f3f4fea
Create Date: 2020-01-19 09:53:21.249292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108c4cf52be6'
down_revision = '5a5b7f3f4fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventories_product_id_fkey', 'inventories', type_='foreignkey')
    op.create_foreign_key(None, 'inventories', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_request_product_id_fkey', 'product_request', type_='foreignkey')
    op.create_foreign_key(None, 'product_request', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('purchase_orders_product_id_fkey', 'purchase_orders', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_orders', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quarterly_request_product_id_fkey', 'quarterly_request', type_='foreignkey')
    op.create_foreign_key(None, 'quarterly_request', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quarterly_request', type_='foreignkey')
    op.create_foreign_key('quarterly_request_product_id_fkey', 'quarterly_request', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.create_foreign_key('purchase_orders_product_id_fkey', 'purchase_orders', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_request', type_='foreignkey')
    op.create_foreign_key('product_request_product_id_fkey', 'product_request', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'inventories', type_='foreignkey')
    op.create_foreign_key('inventories_product_id_fkey', 'inventories', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
