"""empty message

Revision ID: 4126ea31825a
Revises: ccb6b2491e64
Create Date: 2019-07-23 16:36:07.837964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4126ea31825a'
down_revision = 'ccb6b2491e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('vendor', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventories', 'vendors', ['vendor'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventories', type_='foreignkey')
    op.drop_column('inventories', 'vendor')
    # ### end Alembic commands ###
