"""empty message

Revision ID: 41e39419bec7
Revises: dab672078955
Create Date: 2020-03-22 20:28:25.869236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e39419bec7'
down_revision = 'dab672078955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_request', sa.Column('contact_person', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_request', 'contact_person')
    # ### end Alembic commands ###
