"""empty message

Revision ID: 58d629d1d510
Revises: 2e853079129f
Create Date: 2019-07-05 18:32:55.208226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d629d1d510'
down_revision = '2e853079129f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('file_url', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('language', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'language')
    op.drop_column('products', 'file_url')
    # ### end Alembic commands ###
