"""empty message

Revision ID: 598f2fefb7a4
Revises: 8f6cf555e310
Create Date: 2019-07-18 15:45:31.876877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598f2fefb7a4'
down_revision = '8f6cf555e310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('status', sa.String(length=30), nullable=False))
    op.alter_column('vendors', 'contact_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'contact_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('purchase_orders', 'status')
    # ### end Alembic commands ###
