"""empty message

Revision ID: 5a5b7f3f4fea
Revises: dbd10fbf8e27
Create Date: 2019-12-15 08:53:02.958871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5b7f3f4fea'
down_revision = 'dbd10fbf8e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('gst_number', sa.String(length=16), nullable=True))
    op.drop_column('vendors', 'GST')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('GST', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('vendors', 'gst_number')
    # ### end Alembic commands ###
