"""empty message

Revision ID: 6d5fa06c72e9
Revises: dc3b2e8c945b
Create Date: 2019-07-20 13:59:06.333946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5fa06c72e9'
down_revision = 'dc3b2e8c945b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('version', sa.String(length=30), nullable=True))
    op.drop_column('purchase_orders', 'version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('version', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('products', 'version')
    # ### end Alembic commands ###
