"""empty message

Revision ID: 8f6cf555e310
Revises: cf68068fdd7e
Create Date: 2019-07-13 12:06:02.899408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6cf555e310'
down_revision = 'cf68068fdd7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('vendor', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'purchase_orders', 'vendors', ['vendor'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'vendor')
    # ### end Alembic commands ###
