"""empty message

Revision ID: ccb6b2491e64
Revises: 6d5fa06c72e9
Create Date: 2019-07-22 15:47:38.801732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb6b2491e64'
down_revision = '6d5fa06c72e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('vendor', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'vendors', ['vendor'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'vendor')
    # ### end Alembic commands ###
