"""empty message

Revision ID: cf68068fdd7e
Revises: 3da1ed99d67a
Create Date: 2019-07-13 11:56:33.035131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf68068fdd7e'
down_revision = '3da1ed99d67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('date_added', sa.String(length=30), nullable=False),
    sa.Column('date_modified', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
