"""empty message

Revision ID: dab672078955
Revises: f37f5901ee49
Create Date: 2020-02-24 15:18:22.501354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab672078955'
down_revision = 'f37f5901ee49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('order_number', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'order_number')
    # ### end Alembic commands ###
