"""empty message

Revision ID: dbd10fbf8e27
Revises: 6e4b22c05ad1
Create Date: 2019-11-17 10:35:19.044045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd10fbf8e27'
down_revision = '6e4b22c05ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'threshold')
    # ### end Alembic commands ###
