"""empty message

Revision ID: dc3b2e8c945b
Revises: 598f2fefb7a4
Create Date: 2019-07-19 22:18:12.903736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3b2e8c945b'
down_revision = '598f2fefb7a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('version', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'version')
    # ### end Alembic commands ###
