"""empty message

Revision ID: e312d438f97c
Revises: 4126ea31825a
Create Date: 2019-07-29 22:24:46.884559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e312d438f97c'
down_revision = '4126ea31825a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_request', sa.Column('team', sa.String(length=100), nullable=True))
    op.alter_column('product_request', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('product_request', 'organisation',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('product_request', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_request', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('product_request', 'organisation',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('product_request', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('product_request', 'team')
    # ### end Alembic commands ###
