"""empty message

Revision ID: f37f5901ee49
Revises: 460b0528c202
Create Date: 2020-01-20 02:53:21.477363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37f5901ee49'
down_revision = '460b0528c202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_request', sa.Column('returns', sa.String(length=50), nullable=True))
    op.drop_column('product_request', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_request', sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('product_request', 'returns')
    # ### end Alembic commands ###
